### ISSUE TITLE
fstab not populated with xfs

### ISSUE THREAD

**Issue by magnusthorne** [atrull/filesystem_cookbook#15]
xfs isn't being used in my fstab.

From my code:
filesystem "mnt_raid" do
  device "/dev/md0"
  mount "/mnt"
  fstype "xfs"
  options "noatime,nodiratime,nobarrier,inode64"
  action [:create, :enable, :mount]
end

From my chef-client debug:
none on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
/dev/md0 on /mnt type xfs (rw,noatime,nodiratime,attr2,nobarrier,inode64,logbsize=256k,sunit=512,swidth=1024,noquota)
[2015-04-14T17:39:55-07:00] DEBUG: Special device /dev/md0 mounted as /mnt

From my /etc/fstab:
/dev/md0 /mnt auto noatime,nodiratime,nobarrier,inode64 0 0

Note the auto instead of xfs.  If I manually change to xfs and reboot, the disk is mounted.  It doesn't auto mount when set to auto.

**Comment by atrull** [comment]
Hi Magnus,

Thanks for providing the chef resource config

Can you confirm which version of the cookbook you're using ?

I'll investigate this weekend when I have some free time.

Alex

**Comment by magnusthorne** [comment]
Alex,

$ cat Berksfile
metadata

cookbook 'filesystem', '~> 0.9.0'
cookbook 'sysctl', '~> 0.6.2'
cookbook 'ephemeral_raid', '~> 0.0.7'

I should be using 0.10.0

thanks,
-Magnus

**Comment by atrull** [comment]
Hi Magnus,

I replicated your issue.

I've fixed this in version 0.10.1

Very simple fix :-)

Cheers

Alex

**Comment by magnusthorne** [comment]
Thank you Alex!

-Magnus
