### ISSUE TITLE
-f, force option

### ISSUE THREAD

**Issue by erkolson** [atrull/filesystem_cookbook#18]
Hello, on some systems the the mkfs force option is -F, not -f.

On CentOS 7, -f is the fragment-size option

Code is here, I believe:
https://github.com/atrull/filesystem_cookbook/blob/master/providers/default.rb#L136

**Comment by atrull** [comment]
I haven't verified.. but would you be comfortable writing a patch for this, Erik ?

**Comment by erkolson** [comment]
Yeah, I would like to patch it but am under a tight timeline right now.  I won't be able to get to it for some time - new baby coming and trying to wrap up lots of things before that happens.

**Comment by atrull** [comment]
hi Erik can you confirm what filesystems you were creating ? just to be sure.

**Comment by atrull** [comment]
This is looking good to me :-) I'd appreciate some testing.

**Comment by atrull** [comment]
I'm closing this out. I will do another release. Please check it out if you can.

**Comment by erkolson** [comment]
Sorry I missed your comment, I have used it with XFS and EXT4, perhaps EXT3 as well but not for sure.

**Comment by atrull** [comment]
it will use different -f/-F now based on the filesystem (xfs or extX).
