### ISSUE TITLE
Chef-client 12.5.1+ Compatibility

### ISSUE THREAD

**Issue by GitBytes** [atrull/filesystem_cookbook#19]
@atrull @atrullmdsol @dmlb2000

Hi Alex,

I don't have a lot of information yet in terms of output I can post but I can attempt to gather some case information on this issue if need be.. However what I do have is this..

It would seem that Chef has added some features to it's mount resource that aren't being referenced here, specifically how "device_type" options ( device, label, uuid) are made available to chef now but are not handled by this cookbook seemingly. We haven't made steps in our configuration to try and correct this yet via our fork but we can try perhaps, just wanted to see if you are actively working this yet before we made that leap. It may be a good idea to look over the current resource options available now and add them appropriately in another major rev bump branch. As of chef-client 12.5.1 this cookbook seems useless in certain cases where you have specifically a label and not mounting a device directly, 12.4.x worked fine. The chef run gets confused thinking that something has changed in the mount options when in reality it hasn't. Overall, I would just recommend running some kitchen cases against this cookbook to verify it is or is not compatible with 12.5.1+ chef-client, otherwise it may fall to the wayside, even though this is a very useful toolset you have going. Thanks very much in advance.

Best Regards,
GitBytes (Ian)

**Comment by atrull** [comment]
Excuse the delay, but I will try to give this some attention in the next weeks.

**Comment by spliskamatyshak** [comment]
I've experienced this also.  The recipe syntax doesn't do anything. The role syntax works, except if the filesystem already exists and is in use, fails chef-client runs as it appears to try to unmount the in-use filesystem.

**Comment by atrull** [comment]
I believe the latest master fixes the mount issue @spliskamatyshak

**Comment by atrull** [comment]
My latest master (0.10.5+ is working in recipe syntax @spliskamatyshak could you take a look if it works for you ?

include_recipe "filesystem"

filesystem "fs" do
  device "/dev/mapper/fs"
  fstype "xfs"
  mount "/mnt/cryptfs"
  action [:create, :mount]
end

filesystem "fs2" do
  device "/dev/mapper/fs2"
  fstype "xfs"
  force true
  mount "/mnt/cryptfs2"
  action [:create, :mount]
end

**Comment by atrull** [comment]
in addition to force I have added an ignore_existing boolean. it forced to ignore existing filesystems if there isn't one mountable off the blockdevice.

**Comment by atrull** [comment]
I will do a new release to address everything but the device_type  - I need to address the device_type better in separate release after more thought.

**Comment by GitBytes** [comment]
@atrull 
Thank you for looking into the issue. We have not gotten a chance to test but I just wanted to extend my thanks. Cheers!

BR, Ian (GitBytes)

**Comment by atrull** [comment]
NP Ian, I have been testing with 12.6.0 chef-client FWIW.

**Comment by drags** [comment]
Heads up that the remount issue @spliskamatyshak is seeing is due to the `mount` resource within Chef, see https://github.com/chef/chef/issues/4056

Current workarounds are based on adding guards to mount resources, which limits the effectiveness of the `mount` resource, but prevents potentially catastrophic remounts (and large amounts of chef run failures)

**Comment by GitBytes** [comment]
@atrull I am going to close this issue for now so it isn't outstanding for you any longer. I am thinking this direct issue has been resolved. We can reopen it if need be. Thanks again for your help with this. - Ian
